project 'PasseiHTTPCertificate.xcodeproj'

use_frameworks!

platform :ios, '10.0'

target 'PasseiHTTPCertificate_Example' do
  pod 'PasseiHTTPCertificate', :path => '../'

  target 'PasseiHTTPCertificate_Tests' do
    inherit! :search_paths
  end
end
