use_frameworks!

platform :ios, '10.0'

target 'PasseiHTTPCertificate_Example' do
  pod 'PasseiHTTPCertificate', :path => '../'

  target 'PasseiHTTPCertificate_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
